Repository GlowstoneMC/Glowstone, pull requests merged in 2018-02, with the labels that each got.

#851 Fix #848
  src/main/java/net/glowstone/entity/GlowEntity.java
Labels: Status: review

#855 Fix snow slab stacking
  src/main/java/net/glowstone/block/blocktype/BlockSnow.java
Labels: Category: gameplay feature, Priority: minor, Status: review, Type: bug

#842 Migrate non-PowerMock unit tests to Jupiter
  pom.xml
  src/test/java/net/glowstone/block/BuiltinMaterialValueManagerTest.java
  src/test/java/net/glowstone/block/ItemTypesTest.java
  src/test/java/net/glowstone/block/itemtype/ItemBowTest.java
  src/test/java/net/glowstone/block/itemtype/ItemProjectileTest.java
  src/test/java/net/glowstone/block/itemtype/ItemTypeTest.java
  src/test/java/net/glowstone/command/GameModeUtilsTest.java
  src/test/java/net/glowstone/constants/AchievementTest.java
  src/test/java/net/glowstone/constants/BiomeTest.java
  src/test/java/net/glowstone/constants/DisplaySlotTest.java
  src/test/java/net/glowstone/constants/EnchantmentTest.java
  src/test/java/net/glowstone/constants/ItemIdsTest.java
  src/test/java/net/glowstone/constants/ParticleTest.java
  src/test/java/net/glowstone/constants/PotionEffectTest.java
  src/test/java/net/glowstone/constants/StatisticTest.java
  src/test/java/net/glowstone/entity/MetadataIndexTest.java
  src/test/java/net/glowstone/inventory/PlayerInventoryTest.java
  src/test/java/net/glowstone/inventory/WindowClickLogicTest.java
  src/test/java/net/glowstone/inventory/crafting/BasicCraftingTest.java
  src/test/java/net/glowstone/net/BaseProtocolTest.java
  src/test/java/net/glowstone/util/InventoryUtilTest.java
  src/test/java/net/glowstone/util/NamespacedKeyTest.java
  src/test/java/net/glowstone/util/PositionTest.java
  src/test/java/net/glowstone/util/SoundUtilTest.java
  src/test/java/net/glowstone/util/VariableValueArrayTest.java
  src/test/java/net/glowstone/util/collection/SuperIteratorTest.java
  src/test/java/net/glowstone/util/collection/SuperListAndIteratorTest.java
  src/test/java/net/glowstone/util/collection/SuperSetTest.java
  src/test/java/net/glowstone/util/mojangson/MojangsonParseTest.java
  src/test/java/net/glowstone/util/mojangson/MojangsonWriteTest.java
  src/test/java/net/glowstone/util/nbt/CompoundTagTest.java
  src/test/java/net/glowstone/util/nbt/NbtInputTest.java
  src/test/java/net/glowstone/util/nbt/NbtOutputTest.java
Labels: Category: development, Status: review
